services:
  db:
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - app_net

  api:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=crm_db;Username=crm_user;Password=${POSTGRES_PASSWORD}"

  frontend:
    build:
      args:
        VITE_ENVIRONMENT: development
